language: php

php:
  - 5.4

env:
  - MONGO_VERSION=1.3.2
  - MONGO_VERSION=1.3.3

services: mongodb

before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev --prefer-source
